import wx

ID_DIRTREE_OPEN = wx.NewId()
ID_DIRTREE_RENAME = wx.NewId()
ID_DIRTREE_DELETE = wx.NewId()
ID_DIRTREE_NEW_FOLDER = wx.NewId()
ID_DIRTREE_EXPAND_ALL = wx.NewId()
ID_DIRTREE_COLLAPSE_ALL = wx.NewId()

IM_FOLDER = 0
IM_FOLDER_DENIED = 1
IM_FILE = 2

NODE_UNPOPULATED = 0
NODE_POPULATING = 1
NODE_POPULATED = 2
