__all__ = """\
FIND_NEXT
FIND_PREV
SEARCH
GO_TO_LINE
COMMENT
UNCOMMENT
JOIN_LINES
SPLIT_LINES
SORT_LINES
SORT_LINES_CASE_INSENSITIVE
UNIQUE_LINES
REVERSE_LINES
SHUFFLE_LINES
TABS_TO_SPACES
REMOVE_TRAILING_SPACE
REMOVE_LEADING_SPACE
ALIGN_COLUMNS
REMOVE_EXTRA_SPACE
LOWER_CASE
UPPER_CASE
TITLE_CASE
SWAP_CASE
NEW_PROJECT
OPEN_PROJECT
CLOSE_PROJECT
EDIT_PROJECT
CONFIGURE_GLOBAL_COMMANDS
CONFIGURE_PROJECT_COMMANDS
VIEW_SETTINGS
FULL_SCREEN
SHOW_PANE_FILE_BROWSER
SHOW_PANE_TERMINAL
SHOW_PANE_SEARCH
REPORT_BUG
DIRTREE_EDIT
DIRTREE_OPEN_IN_WEB_VIEW
DIRTREE_OPEN_FOLDER
DIRTREE_SEARCH
DIRTREE_SEARCH_FOLDER
COPY_FILE_PATH
OPEN_CONTAINING_FOLDER
OPEN_IN_WEB_VIEW
WEB_SEARCH
""".strip().split()

def init():
    import sys, wx
    module = sys.modules[__name__]
    wxids = []
    for id_name in dir(wx):
        if id_name.startswith("ID_"):
            setattr(module, id_name[3:], getattr(wx, id_name))
            wxids.append(id_name[3:])
    for id_name in __all__:
        if not hasattr(module, id_name):
            setattr(module, id_name, wx.NewId())
    __all__.extend(wxids)

init()
del init

from dirtree_constants import (
    ID_DIRTREE_OPEN as DIRTREE_OPEN,
    ID_DIRTREE_RENAME as DIRTREE_RENAME,
    ID_DIRTREE_DELETE as DIRTREE_DELETE,
    ID_DIRTREE_NEW_FOLDER as DIRTREE_NEW_FOLDER,
    ID_DIRTREE_EXPAND_ALL as DIRTREE_EXPAND_ALL,
    ID_DIRTREE_COLLAPSE_ALL as DIRTREE_COLLAPSE_ALL)
