default_theme = [
    ("character",              "fore:#7F007F"),
    ("classname",              "fore:#0000FF,bold"),
    ("comment",                "fore:#7F7F7F"),
    ("commentblock",           "fore:#7F7F7F"),
    ("commentdoc",             "fore:#7F7F7F"),
    ("commentdockeyword",      "fore:#7F7F7F"),
    ("commentdockeyworderror", "fore:#7F7F7F"),
    ("commentline",            "fore:#7F7F7F"),
    ("commentlinedoc",         "fore:#7F7F7F"),
    ("decorator",              "fore:#7F7F00,bold"),
    ("default",                "fore:#000000"),
    ("defname",                "fore:#007F7F,bold"),
    ("globalclass",            "fore:#000000"),
    ("identifier",             "fore:#000000"),
    ("keyword",                "fore:#00007F,bold"),
    ("keyword2",               "fore:#00007F,bold"),
    ("number",                 "fore:#007F7F"),
    ("operator",               "bold"),
    ("preprocessor",           "fore:#007F7F"),
    ("regex",                  "fore:#000000"),
    ("string",                 "fore:#7F007F"),
    ("stringeol",              "fore:#000000,back:#E0C0E0,eol"),
    ("triple",                 "fore:#7F0000"),
    ("tripledouble",           "fore:#7F0000"),
    ("uuid",                   "fore:#000000"),
    ("verbatim",               "fore:#000000"),
]
