#!/bin/bash
WXVER=2.9.4.0
BUILD_DIR=/tmp/wxbuild
rm -rf "${BUILD_DIR}/wxPython-src-${WXVER}" "${BUILD_DIR}/wx"
mkdir -p "${BUILD_DIR}"
cd "${BUILD_DIR}"
set -o errexit
if [ ! -e wxPython-src-${WXVER}.tar.bz2 ]; then
    curl -O http://downloads.sourceforge.net/project/wxpython/wxPython/${WXVER}/wxPython-src-${WXVER}.tar.bz2
fi
rm -rf wxPython-src-${WXVER}
tar xvjf wxPython-src-${WXVER}.tar.bz2
cd wxPython-src-${WXVER}
export WXWIN="$PWD"
cd build
"${WXWIN}/configure" \
    --disable-rpath \
    --enable-debug=no \
    --enable-optimise \
    --enable-monolithic \
    --enable-unicode \
    --enable-webview \
    --enable-webview-webkit \
    --with-gtk \
    --with-expat=builtin \
    --with-libpng=builtin \
    --with-libjpeg=builtin \
    --with-libtiff=builtin \
    --with-zlib=no \
    --with-regex=no
make -j 8
cd "${WXWIN}/wxPython"
export LDFLAGS=-Wl,-rpath=\\\$ORIGIN
python2.7 setup.py build_ext --inplace \
    UNICODE=1 \
    MONOLITHIC=1 \
    WX_CONFIG="${WXWIN}/build/wx-config" \
    BUILD_GLCANVAS=0
cd "${WXWIN}"
mv wxPython/wx ../
cp build/lib/libwx_gtk2u*.so.4 ../wx/
cd ..
strip -s -R .comment wx/*.so*
rm -rf wxPython-src-${WXVER}
