#!/bin/bash

DEST_DIR="$PWD"
BUILD_DIR=/tmp/tmp-aur
TOOLS_DIR="`dirname $(readlink -f $0)`"

rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"
mkdir devo
cd devo
cp "$TOOLS_DIR/arch-pkgbuild" PKGBUILD
cp "$TOOLS_DIR/arch-install" devo.install
makepkg --source
mv devo*.src.tar.gz "$DEST_DIR"
cd "$DEST_DIR"
rm -rf "$BUILD_DIR"
