#!/bin/bash

DEST_DIR="$PWD"
BUILD_DIR=/tmp/devo-build
TOOLS_DIR="`dirname $(readlink -f $0)`"

rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"
cp "$TOOLS_DIR/arch-pkgbuild" PKGBUILD
cp "$TOOLS_DIR/arch-install" devo.install
makepkg
mv devo-*.pkg.tar.xz "$DEST_DIR"
cd "$DEST_DIR"
rm -rf "$BUILD_DIR"
